#!/bin/bash

# [!] Do not rename this file to `bash_completion`
#     as it will create an infinite loop!

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi


#Completion for WP-CLI: http://wp-cli.org/

if [ -f "$HOME/.wp-cli/wp-completion.bash" ]; then "$HOME/.wp-cli/wp-completion.bash"; fi


#GCloud
# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/google-cloud-sdk/path.bash.inc" ]; then source "$HOME/google-cloud-sdk/path.bash.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "$HOME/google-cloud-sdk/completion.bash.inc" ]; then source "$HOME/google-cloud-sdk/completion.bash.inc"; fi

